In [2]:
import pandas as pd
import numpy as np

import nltk
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import f1_score

import matplotlib.pyplot as plt

In [3]:
#reading the file

df = pd.read_csv("data.csv")

In [4]:
df

COMMENT_ID  \
0    LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU   
1    LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A   
2    LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8   
3            z13jhp0bxqncu512g22wvzkasxmvvzjaz04   
4            z13fwbwp1oujthgqj04chlngpvzmtt3r3dw   
..                                           ...   
345            z13th1q4yzihf1bll23qxzpjeujterydj   
346        z13fcn1wfpb5e51xe04chdxakpzgchyaxzo0k   
347          z130zd5b3titudkoe04ccbeohojxuzppvbg   
348          z12he50arvrkivl5u04cctawgxzkjfsjcc4   
349        z13vhvu54u3ewpp5h04ccb4zuoardrmjlyk0k   

                                   AUTHOR                 DATE  \
0                               Julius NM  2013-11-07T06:20:48   
1                             adam riyati  2013-11-07T12:37:15   
2                        Evgeny Murashkin  2013-11-08T17:34:21   
3                         ElNino Melendez  2013-11-09T08:28:43   
4                                  GsMega  2013-11-10T16:05:38   
..                                    ...                  ...   
345                       Carmen Racasanu  2014-11-14T13:27:52   
346                       diego mogrovejo  2014-11-14T13:28:08   
347  BlueYetiPlayz -Call Of Duty and More  2015-05-23T13:04:32   
348                          Photo Editor  2015-06-05T14:14:48   
349                            Ray Benich  2015-06-05T18:05:16   

                                               CONTENT  CLASS  
0    Huh, anyway check out this you[tube] channel: ...      1  
1    Hey guys check out my new channel and our firs...      1  
2               just for test I have to say murdev.com      1  
3     me shaking my sexy ass on my channel enjoy ^_^       1  
4              watch?v=vtaRGgvGtWQ   Check this out .      1  
..                                                 ...    ...  
345  How can this have 2 billion views when there's...      0  
346         I don't now why I'm watching this in 2014      0  
347  subscribe to me for call of duty vids and give...      1  
348  hi guys please my android photo editor downloa...      1  
349  The first billion viewed this because they tho...      0  

[350 rows x 5 columns]

In [5]:
#checking if balanced data

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   COMMENT_ID  350 non-null    object
 1   AUTHOR      350 non-null    object
 2   DATE        350 non-null    object
 3   CONTENT     350 non-null    object
 4   CLASS       350 non-null    int64 
dtypes: int64(1), object(4)
memory usage: 13.8+ KB


In [6]:
#taking the content column from the data frame

contents = df['CONTENT']

In [7]:
contents

0      Huh, anyway check out this you[tube] channel: ...
1      Hey guys check out my new channel and our firs...
2                 just for test I have to say murdev.com
3       me shaking my sexy ass on my channel enjoy ^_^ 
4                watch?v=vtaRGgvGtWQ   Check this out .
                             ...                        
345    How can this have 2 billion views when there's...
346           I don't now why I'm watching this in 2014
347    subscribe to me for call of duty vids and give...
348    hi guys please my android photo editor downloa...
349    The first billion viewed this because they tho...
Name: CONTENT, Length: 350, dtype: object

In [8]:
#cleaning the dataset; converting to lower; splits into list; removal of stopwords; and Stemming
ps = PorterStemmer()
corpus = []

for i in range(0, len(contents)):
    review = re.sub('[^a-zA-Z]', ' ', contents[i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [9]:
corpus

['huh anyway check tube channel kobyoshi',
 'hey guy check new channel first vid us monkey monkey white shirt pleas leav like comment pleas subscrib',
 'test say murdev com',
 'shake sexi ass channel enjoy',
 'watch v vtarggvgtwq check',
 'hey check new websit site kid stuff kidsmediausa com',
 'subscrib channel',
 'turn mute soon came want check view',
 'check channel funni video',
 'u check channel tell next',
 'hey subscrib',
 'start read stop subscrib within one day entir famili die want stay aliv subscrib right',
 'http twitter com gbphotographygb',
 'subscrib like comment',
 'pleas like http premium easypromosapp com votem',
 'hello like game art video scientif experi tutori lyric video much much pleas check channel subscrib start soon hope abl cover expect also check got far',
 'check view',
 'http www ebay com itm sspagenam strk meselx amp trksid p l',
 'http ubuntuon com beuutvu zkxk utgpz k',
 'edm apparel compani dedic bring music inspir design cloth perfect rave music festi

In [10]:
#convert the corpus to vectors; prepping the data

tfidfcv = TfidfVectorizer()
X = tfidfcv.fit_transform(corpus).toarray()

In [11]:
#independent variable
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [12]:
#dependent variable
y=df['CLASS']

In [13]:
y

0      1
1      1
2      1
3      1
4      1
      ..
345    0
346    0
347    1
348    1
349    0
Name: CLASS, Length: 350, dtype: int64

In [14]:
# Train Test Split - split the independent and dependent variables from 80-20 split. Test size is 20%. 

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

# 1. Naive Bayes Multinomial Model 

In [15]:
# Training model using Naive bayes classifier

from sklearn.naive_bayes import MultinomialNB

NB_model = MultinomialNB().fit(X_train, y_train)

In [16]:
y_pred=NB_model.predict(X_test)

In [17]:
#confusion matrix - to determine the positive and negative results of the model. 
#Comparing the y_test labels (20% of the original dataset messages) Then, compare the prediction made by the model in y_pred

from sklearn.metrics import confusion_matrix
confusion_mat = confusion_matrix(y_test,y_pred)

In [18]:
confusion_mat

array([[35,  4],
       [ 1, 30]], dtype=int64)

In [19]:
accuracy = f1_score(y_test,y_pred)
accuracy

0.923076923076923

# 2. Passive Aggressive Classifier Algorithm

In [20]:
from sklearn.linear_model import PassiveAggressiveClassifier

linear_clf = PassiveAggressiveClassifier()

In [21]:
linear_clf.fit(X_train,y_train)

PassiveAggressiveClassifier()

In [22]:
y_pred=linear_clf.predict(X_test)

In [23]:
from sklearn.metrics import confusion_matrix
confusion_mat = confusion_matrix(y_test,y_pred)

In [24]:
confusion_mat

array([[37,  2],
       [ 0, 31]], dtype=int64)

In [25]:
accuracy = f1_score(y_test,y_pred)
accuracy

0.96875

# 3. Building Own Model using LSTM

In [26]:
import tensorflow as tf

In [27]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [28]:
voc_size=2000
sent_length=20

In [29]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[968, 1188, 1469, 536, 345, 1197],
 [1966,
  377,
  1469,
  1829,
  345,
  853,
  1789,
  905,
  330,
  330,
  1217,
  1177,
  1358,
  106,
  320,
  507,
  1358,
  1664],
 [189, 721, 1324, 689],
 [512, 583, 645, 345, 1903],
 [400, 301, 161, 1469],
 [1966, 1469, 1829, 1894, 1530, 442, 1952, 463, 689],
 [1664, 345],
 [999, 390, 1620, 713, 1826, 1469, 836],
 [1469, 345, 173, 718],
 [964, 1469, 345, 1936, 1770],
 [1966, 1664],
 [640,
  637,
  1420,
  1664,
  1087,
  1767,
  938,
  444,
  238,
  1527,
  1826,
  91,
  1818,
  1664,
  554],
 [1646, 1403, 689, 607],
 [1664, 320, 507],
 [1358, 320, 1646, 435, 1464, 689, 1519],
 [575,
  320,
  1417,
  771,
  718,
  705,
  159,
  13,
  1855,
  718,
  1706,
  1706,
  1358,
  1469,
  345,
  1664,
  640,
  1620,
  1255,
  1375,
  1340,
  1273,
  197,
  1469,
  1725,
  683],
 [1469, 836],
 [1646, 1558, 1968, 689, 1115, 1424, 87, 675, 435, 1614, 654, 98],
 [1646, 815, 689, 1538, 109, 1163, 1791],
 [670,
  1383,
  1868,
  1138,
  960,
  753,
  1409,
 

In [30]:
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ...  536  345 1197]
 [   0    0 1966 ...  507 1358 1664]
 [   0    0    0 ...  721 1324  689]
 ...
 [   0    0    0 ...  248 1111 1036]
 [1512  377 1358 ...  357  297   45]
 [   0    0    0 ...  708  853 1008]]


In [31]:
## Creating model
embedding_vector_features=40

model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(200))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            80000     
                                                                 
 lstm (LSTM)                 (None, 200)               192800    
                                                                 
 dense (Dense)               (None, 1)                 201       
                                                                 
Total params: 273,001
Trainable params: 273,001
Non-trainable params: 0
_________________________________________________________________
None


In [32]:
#checking data shapes
len(embedded_docs),y.shape

(350, (350,))

In [33]:
#convert to numpy
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [34]:
X_final.shape,y_final.shape

((350, 20), (350,))

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [36]:
### Finally Training
history = model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
4/4 [==============================] - 3s 103ms/step - loss: 0.6921 - accuracy: 0.5128 - val_loss: 0.6902 - val_accuracy: 0.4655
Epoch 2/10
4/4 [==============================] - 0s 20ms/step - loss: 0.6817 - accuracy: 0.5556 - val_loss: 0.6809 - val_accuracy: 0.5259
Epoch 3/10
4/4 [==============================] - 0s 20ms/step - loss: 0.6637 - accuracy: 0.6282 - val_loss: 0.6734 - val_accuracy: 0.5862
Epoch 4/10
4/4 [==============================] - 0s 19ms/step - loss: 0.6366 - accuracy: 0.6667 - val_loss: 0.6286 - val_accuracy: 0.7155
Epoch 5/10
4/4 [==============================] - 0s 20ms/step - loss: 0.5997 - accuracy: 0.7436 - val_loss: 0.5746 - val_accuracy: 0.7069
Epoch 6/10
4/4 [==============================] - 0s 20ms/step - loss: 0.5282 - accuracy: 0.7265 - val_loss: 0.5045 - val_accuracy: 0.7759
Epoch 7/10
4/4 [==============================] - 0s 20ms/step - loss: 0.4921 - accuracy: 0.7863 - val_loss: 0.4448 - val_accuracy: 0.7845
Epoch 8/10
4/4 [==========

In [37]:
pred_test = model.predict(X_test)

4/4 [==============================] - 0s 5ms/step


In [38]:
#Evaluation on Training Data

for item in history.history:
    print("Final", item, ":", history.history[item][-1])

Final loss : 0.29132795333862305
Final accuracy : 0.8589743375778198
Final val_loss : 0.3248068690299988
Final val_accuracy : 0.9051724076271057


# BEST Model: Passive Aggressive Classifier Algorithm 

In [39]:
import pickle

#best model fileout
filename = 'spamclassifier.pkl'
pickle.dump(linear_clf, open(filename, 'wb'))

In [40]:
#data out

pickle.dump(tfidfcv, open('spamdata.pkl', 'wb'))